special:
    everyone:
        can: 
            - say
            - tag
        config:
            tag:
              only:
                 - help
                 - resolved
            say:
              only:
                 - a
                 - b
                 - c
                
users:
    tacaswell:
        can:
            - merge
            - tag
    choldgraf:
        can:
            - say
            - open
            - close
            - tag
            - untag
            - merge
    Carreau:
        can:
            - merge
            - debug
            - tag
        config:
            debug: 
                - A1
                - B2
            tag:
              only:
                 - help
                 - resolved
                 - super

    nellev:
        can:
            - say
            - tag
            - close
            - open
            - merge
    staeiou:
        can:
            - say
            - tag
            - untag
            - merge
