users:
    Carreau:
        can:
            - say
            - close
            - open
            - merge
            - tag
    nellev:
        can:
            - say
            - tag
            - close
            - open
            - merge
    staeiou:
        can:
            - say
            - tag
            - untag
            - merge
