special:
    everyone:
        can: 
            - say
            - tag
        config:
            say:
                - "say specific"
                - "config values"
                
users:
    tacaswell:
        can:
            - merge
            - tag
    choldgraf:
        can:
            - say
            - open
            - close
            - tag
            - untag
            - merge
    Carreau:
        can:
            - merge
            - debug
        config:
            - debug: 
                - A1
                - B2

    nellev:
        can:
            - say
            - tag
            - close
            - open
            - merge
    staeiou:
        can:
            - say
            - tag
            - untag
            - merge
